In the previous example, we started from data stored in multidimensional Numpy arrays, also called `tensors`. In general, all current machine-learning systems use tensors as their basic data structure. 
At it's core, a tensor is a container for data. So it's a container for numbers. Tensors are a generalization of matrices to an arbitrary number of dimensions.

#### 2.2.1 Scalars (0D tensors)

A tensor that contains only one number is called a `scalar` (or a scalar tensor, or 0-dimensional tensor, or 0D tensor). In  Numpy, a `float32` or `float64` number is a scalar tensor. You can display the number of axes of a Numpy tensor via the `ndim` attribute. A scalar tensor has 0 axes `ndim == 0`. The number of axes of a tensor is also called its `rank`

In [1]:
import numpy as np
x = np.array(12)
x

array(12)

In [2]:
x.ndim

0

#### 2.2.2 Vectors (1D tensors)

An array of numbers is called a `vector`, or 1D tensor. A 1D tensor is said to have exactly one axis.

In [3]:
x = np.array([12, 3, 6, 14, 8])
x

array([12,  3,  6, 14,  8])

In [4]:
x.ndim

1

This vector has five entries and so is called a `5-dimensional vector`. Don't confuse a 5D vector with a 5D tensor. A 5D vector has only one axis and has five dimensions along its axis, whereas a 5D tensor has five axes (and may have any number of dimensions along each axis). `Dimensionality` can denote either the number of entries along a specific axis (as in the case of our 5D vector) or the number of axes in a tensor (such as a 5D tensor), which can be confusing at times. In the latter case, it's technically more correct to talk about `a tensor of rank 5` (the rank of a tensor being the number of axes), but the ambiguous notation 5D `tensor` is common regardless. 

#### 2.2.3 Matrices (2D tensors)

An array of vectors is a `matrix`, or 2D tensor. A matrix has two axes (often referred to `rows` and `columns`). You can visually interpret a matrix as a rectangular grid of numbers.

In [5]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [6]:
x.ndim

2

The entries from the first axis are called the `rows`, and the entries from the second axis are called the `columns`. In the previous example, [5, 78, 2, 34, 0] is the first row of x, and [5, 6, 7] is the first column.

#### 2.24 3D tensors and higher-dimensional tensors

If you pack such matrices in a new array, you obtain a 3D tensor, which you can visually interpret as a cube of numbers.

In [7]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [8]:
x.ndim

3

By packing 3D tensors in an array, you can create a 4D Tensor, and so on. In deep learning, you'll generally manipulate tensors that are 0D to 4D, although you may go up to 5D if you process video data.

#### 2.2.5 Key attributes

A tensor is defined by three key attributes:
- `Number of axes (rank)` For instance, a 3D tensor has three axes, and a matrix has two axes. This is also called the tensor's `ndim` in Python libraries such as Numpy.
- `Shape` This is a tuple of integers that describes how many dimensions the tensor has along each axis. For instance, the previous matrix example has shape (3, 5), and the 3D tensor example has shape (3, 3, 5). A vector has a shape with single element, such as (5, ), whereas a scalar has an empty shape. ().
- `Data type` This is the type of the data contained in the tensor; for instance, a tensor's type could be `float32`, `uint8`, `float64`, and so on. On rare occasions, you may see a `char` tensor. Note that string tensors don't exist in Numpy, because tensors live in preallocated, contiguous memory segments and string, being variable length, would preclude the use of this implementation

To make this more concrete, let's look back at the data we processed in the MNIST example.

In [9]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [10]:
# Display number oa axes

print(f"Number of axes: {train_images.ndim}")
print(f"Shape of tensor: {train_images.shape}")
print(f"Data type of tensor: {train_images.dtype}")

Number of axes: 3
Shape of tensor: (60000, 28, 28)
Data type of tensor: uint8


So what we have here is a 3D tensor of 8-bit integers. More precisely, it's an array of 60,000 matrices of 28 x 28 integers. Each such matrix is a grayscale image, with coefficients betwenn 0 and 255.
Let's display the fourth digit in this 3D tensor, using the library Matplotlib

In [ ]:
digit = train_images[4]

import matplotlib.pyplot as plt
%matplotlib inline

plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

#### 2.2.6 Manipulating tensors in Numpy

In the previous example, we selected a specific digit alongside the first axis using the syntax `train_images[i]`. Selecting specific elements in a tensor is called `tensor slicing`. Let's look at the tensor-slicing operations you can do on Numpy arrays.
The following example selects digits #10 to #100 (#100 isn't included) and puts them in an array of shape (90, 28, 28)

In [ ]:
my_slice = train_images[10:100]
print(f"Shape of the slice: {my_slice.shape}")

It's equivalent to this more detailed notation, which specifies a start index and stop index for the slice along each tensor axis. Note that `:` is equivalent to selecting the entire axis

In [ ]:
my_slice = train_images[10:100, :, :] # Equivalent to the previous example
print(f"Shape of the slice: {my_slice.shape}")

In [ ]:
my_slice = train_images[10:100, 0:28, 0:28] # Also equivalent to the previous example
print(f"Shape of the slice: {my_slice.shape}")

In general, you may select between any two indices along each tensor axis. For instance, in order to select 14 x 14 pixels in the bottom-right corner of all images

In [ ]:
my_slice = train_images[:, 14:, 14:]

It's also possible to use negative indices. Much like negative indices in python lists, they indicate a position relative to the end of the current axis. In order to crop the images to patches of 14 x 14 pixels centered in the middle

In [ ]:
my_slice = train_images[:, 7:-7, 7:-7]
############dvnsjlvndsvndjln